
AWSTemplateFormatVersion: '2010-09-09'

Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation to create MyAPP Infrastructure'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  S3BucketData:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  MyPipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "pipeline.yml"
      Parameters:
        S3BucketData: !Ref S3BucketData

Outputs:
  S3BucketName:
    Value: S3Bucket 
    Description: Bucket Name
  S3BucketData:
    Value: S3Bucket 
    Description: Bucket Name